/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.dgt;
import Modelo.Vehiculo;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Naia
 */
public class AltaMultas extends javax.swing.JFrame {

    /** Creates new form AltaMultas */
    private LocalDate localDate;
    public AltaMultas() {
        try{
            initComponents();
            dgt.rellenarCombo(cbTipoMulta);
            generarId();
            deshabilitarCampos();
           
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
              
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tflugar = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbColores = new javax.swing.JComboBox<>();
        bBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfidtipomulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoMulta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Asignar una multa");

        jLabel2.setText("ID");

        jLabel4.setText("Lugar de la multa");

        tflugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflugarActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("Matrícula");

        jLabel6.setText("Color");

        jLabel7.setText("Modelo");

        cbColores.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Elegir un color --", "Negro", "Blanco", "Gris", "Rojo", "Azul", "Amarillo", "Verde", " " }));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del tipo de la multa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jLabel3.setText("Tipo de multa");

        cbTipoMulta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbTipoMulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Elegir un tipo de multa --" }));
        cbTipoMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMultaActionPerformed(evt);
            }
        });

        jLabel8.setText("ID de la multa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cbTipoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tfidtipomulta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidtipomulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(bSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbColores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bBuscar))
                                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tflugar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tflugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bSalir))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        dgt.salirAltaMultas();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            dgt.buscarVehiculo(tfMatricula.getText());
            if (validarDatos()==true) {
                if (tfModelo.isEditable()) {
                    if (tfMatricula.getText().isEmpty() || tfModelo.getText().isEmpty()) {
                        JOptionPane.showInputDialog("Tienes que rellenar los datos del vehículo");
                    }else{
                        dgt.añadirVehiculo(tfMatricula.getText(),cbColores.getSelectedItem().toString(),tfModelo.getText());
                        JOptionPane.showMessageDialog(this,"Vehículo añadido");
                        limpiarCampos();
                    }
                }else{
                    if (cbTipoMulta.getSelectedItem().toString().equalsIgnoreCase("-- Elige un tipo de multa --"))
                        JOptionPane.showMessageDialog(this, "Tienes que elegir un tipo de multa");
                    else{
                        dgt.añadirDatos(tfid.getText(),tfidtipomulta.getText(),tflugar.getText(),tfMatricula.getText());
                        JOptionPane.showMessageDialog(this, "Multa asignada");
                        limpiarCampos();
                    }
                }
            }else
                JOptionPane.showMessageDialog(this, "No se han podido añadir los datos a la base de datos");
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        try {
            dgt.buscarVehiculo(tfMatricula.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tflugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflugarActionPerformed

    private void cbTipoMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMultaActionPerformed
        // TODO add your handling code here:
        try {
            dgt.obtenerIdMulta(cbTipoMulta.getSelectedItem().toString());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_cbTipoMultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaMultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbColores;
    private javax.swing.JComboBox<String> cbTipoMulta;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfidtipomulta;
    private javax.swing.JTextField tflugar;
    // End of variables declaration//GEN-END:variables

    
    private boolean validarDatos() {
        try {
            
            validarLugar();
            validarMatricula();
            validarColor();
            validarModelo();
            
            return true;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        }
        
    }


    private void validarLugar() {
        if (tflugar.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"El lugar de la multa es un dato obligatorio");
        else{
            if (tflugar.getText().length()< 3)
                JOptionPane.showMessageDialog(this, "El lugar introducido no es válido");
        }
        
    }

    public void vehiculoNoEncontrado() {
        tfModelo.setEditable(true);
        cbColores.setEditable(true);
    }

    public void vehiculoEncontrado(Vehiculo v) {
        tfModelo.setText(v.getModelo());
        cbColores.setSelectedItem(v.getColor());
    }

    private void validarMatricula() {
        if (tfMatricula.getText().isEmpty()) 
            JOptionPane.showMessageDialog(this,"La matrícula es un dato obligatorio");
        else{
            Pattern patron = Pattern.compile("^[0-9]{4}[A-Z]{3}$");
            Matcher matcher = patron.matcher(tfMatricula.getText());
            if (matcher.matches()) {
            
            }else{
                JOptionPane.showMessageDialog(this,"Matrícula inválida");
            }  
        }
        
         
    }

    private void validarColor() {
        if (cbColores.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "El color es un campo obligatorio");
    }

    private void validarModelo() {
        if (tfModelo.getText().isEmpty()) 
            JOptionPane.showMessageDialog(this,"El modelo es un dato obligatorio");
        else{
           Pattern patron = Pattern.compile("[[A-Z][a-z]{2,}[ 0-9]{0,}]{1,}");
            Matcher matcher = patron.matcher(tfModelo.getText());
            if (matcher.matches()) {
            
            }else
            JOptionPane.showMessageDialog(this, "Modelo inválido"); 
            }
    }

    public void generarId() {
        try{
            int numAleatorio = (int)(Math.random()*99999);
            boolean resultado = dgt.generarIdAutomatico(numAleatorio);
            tfid.setText(String.valueOf(numAleatorio));
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    public void añadirDatosId(String id) {
        tfidtipomulta.setText(id);
    }

    private void limpiarCampos() {
        try{
            tfidtipomulta.setText("");
            tflugar.setText("");
            tfMatricula.setText("");
            tfModelo.setText("");
            deshabilitarCampos();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }

    private void deshabilitarCampos() {
        tfidtipomulta.setEditable(false);
        tfid.setEditable(false); 
        tfModelo.setEditable(false);
        cbColores.setEditable(false);
    }

   

    

}
