/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.dgt;
import Modelo.Vehiculo;
import java.time.LocalDate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Naia
 */
public class AltaMultas extends javax.swing.JFrame {

    /** Creates new form AltaMultas */
    private LocalDate localDate;
    public AltaMultas() {
        try{
            initComponents();
            tfid.setEditable(false); 
            generarId();
            tfModelo.setEditable(false);
            cbColores.setEditable(false);
           
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
              
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoMulta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tflugar = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbColores = new javax.swing.JComboBox<>();
        bBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Añadir una multa");

        jLabel2.setText("ID");

        jLabel3.setText("Tipo de multa");

        cbTipoMulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conducir con exceso de alcohol.", "Conducir con presencia de drogas en el organismo.", "Incumplir la obligación de someterse a las pruebas de detección.", "Conducir de forma temeraria, en sentido contrario o participar en carreras ilegales.", "Conducir vehículos que tengan instalados inhibidores de radares o cinemómetros u otros mecanismos encaminados a interferir en el correcto funcionamiento de los sistemas de vigilancia del tráfico", "Alterar el normal uso del tacógrafo o del limitador de velocidad.", "Conducir sin la clase de permiso o la licencia necesarios.", "No respetar la prioridad de paso las señales de stop y ceda el paso y los semáforos en rojo.", "Arrojar a la vía o en sus inmediaciones objetos que puedan producir incendios, accidentes u obstaculizar la circulación.", "Realizar adelantamientos indebidos.", "Adelantar poniendo en peligro o entorpeciendo a ciclistas.", "Efectuar un cambio de sentido en zonas prohibidas.", "Realizar la maniobra de marcha atrás en autopistas y autovías.", "No respetar las señales de los Agentes que regulan la circulación.", "No respetar la distancia de seguridad.", "Conducir utilizando manualmente el teléfono móvil, programando el navegador, usando auriculares u otros dispositivos que disminuyan la atención.", "No hacer uso del cinturón de seguridad, sistemas de retención infantil, casco y demás elementos de protección.", "Conducir con el permiso suspendido o teniendo prohibido el uso de ese vehículo.", "Conducir vehículos utilizando mecanismos de detección de radares o cinemómetros.", "Exceso de velocidad.", "Vehiculo mal estacionado." }));

        jLabel4.setText("Lugar");

        tflugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflugarActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("Matrícula");

        jLabel6.setText("Color");

        jLabel7.setText("Modelo");

        cbColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Blanco", "Gris", "Rojo", "Azul", "Amarillo", "Verde", " " }));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbColores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bAceptar)
                            .addGap(18, 18, 18)
                            .addComponent(bSalir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tflugar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbTipoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfid)
                                    .addGap(74, 74, 74)))
                            .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bBuscar)
                        .addComponent(tfModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tflugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bBuscar)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bSalir))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        dgt.salirAltaMultas();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            dgt.buscarVehiculo(tfMatricula.getText());
            if (validarDatos()) {
                if (tfModelo.isEditable()) {
                    dgt.añadirVehiculo(tfMatricula.getText(),cbColores.getSelectedItem().toString(),tfModelo.getText());
                    JOptionPane.showMessageDialog(this,"Vehículo añadido");
                }
                dgt.añadirDatos(cbTipoMulta.getSelectedItem().toString(), tflugar.getText(),tfid.getText(),tfMatricula.getText());
            }else
                JOptionPane.showMessageDialog(this, "No se han podido añadir los datos a la base de datos");
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        try {
            dgt.buscarVehiculo(tfMatricula.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tflugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaMultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbColores;
    private javax.swing.JComboBox<String> cbTipoMulta;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tflugar;
    // End of variables declaration//GEN-END:variables

    public void generarId() throws Exception{
        int numAleatorio = (int)(Math.random()*99999);
        boolean resultado = dgt.generarIdAutomatico(numAleatorio);
        tfid.setText(String.valueOf(numAleatorio));
        
    }

    private boolean validarDatos() {
        try {
            validarTipoMulta();
            validarLugar();
            validarMatricula();
            validarColor();
            validarModelo();
            return true;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        }
        
    }

    private void validarTipoMulta() {
        if (cbTipoMulta.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "El tipo de multa es un campo obligatorio");
    }

    private void validarLugar() {
        if (tflugar.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"El lugar de la multa es un dato obligatorio");
        if (tflugar.getText().length()< 3)
            JOptionPane.showMessageDialog(this, "El lugar introducido no es válido");
    }

    public void vehiculoNoEncontrado() {
        tfModelo.setEditable(true);
        cbColores.setEditable(true);
    }

    public void vehiculoEncontrado(Vehiculo v) {
        tfModelo.setText(v.getModelo());
        cbColores.setSelectedItem(v.getColor());
    }

    private void validarMatricula() {
        if (tfMatricula.getText().isEmpty()) 
            JOptionPane.showMessageDialog(this,"La matrícula es un dato obligatorio");
        
        
        Pattern patron = Pattern.compile("^[0-9]{4}[A-Z]{3}$");
        Matcher matcher = patron.matcher(tfMatricula.getText());
        if (matcher.matches()) {
            
        }else{
            JOptionPane.showMessageDialog(this,"Matrícula inválida");
        }   
    }

    private void validarColor() {
        if (cbColores.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "El color es un campo obligatorio");
    }

    private void validarModelo() {
        if (tfModelo.getText().isEmpty()) 
            JOptionPane.showMessageDialog(this,"El modelo es un dato obligatorio");
        
        Pattern patron = Pattern.compile("[[A-Z][a-z]{2,}[ 0-9]{0,}]{1,}");
        Matcher matcher = patron.matcher(tfModelo.getText());
        if (matcher.matches()) {
            
        }else
            JOptionPane.showMessageDialog(this, "Modelo inválido");
    }

   

    

}
