/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ej2.Ej2;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw06
 */
public class Alta extends javax.swing.JFrame {

    /**
     * Creates new form Alta
     */
    public Alta() {
        initComponents();
        lError.setVisible(false);
        lNombreInvalido.setVisible(false);
        lApellidoInvalido.setVisible(false);
        lDniInvalido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        lError = new javax.swing.JLabel();
        lNombreInvalido = new javax.swing.JLabel();
        lApellidoInvalido = new javax.swing.JLabel();
        lDniInvalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("ALTA DE PERSONAS");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Dni");

        bAceptar.setText("Añadir");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lError.setForeground(new java.awt.Color(255, 51, 102));
        lError.setText("* Deben de estar todos los campos rellenos");

        lNombreInvalido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lNombreInvalido.setForeground(new java.awt.Color(255, 51, 102));
        lNombreInvalido.setText("* Nombre inválido");

        lApellidoInvalido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lApellidoInvalido.setForeground(new java.awt.Color(255, 51, 102));
        lApellidoInvalido.setText("* Apellido inválido");

        lDniInvalido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lDniInvalido.setForeground(new java.awt.Color(255, 51, 102));
        lDniInvalido.setText("* Dni inválido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tfApellido)
                                    .addComponent(tfDni))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNombreInvalido)
                                    .addComponent(lApellidoInvalido)
                                    .addComponent(lDniInvalido)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAceptar)
                                .addGap(26, 26, 26)
                                .addComponent(bSalir))
                            .addComponent(lError)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombreInvalido))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lApellidoInvalido))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDniInvalido))
                .addGap(26, 26, 26)
                .addComponent(lError)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bSalir))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        if (tfNombre.getText().isEmpty() || tfApellido.getText().isEmpty() || tfDni.getText().isEmpty()) {
           lError.setVisible(true);
        }else{
            lError.setVisible(false);
            validarNombre(tfNombre.getText());
            validarApellido(tfApellido.getText()); 
            validarDni(tfDni.getText());
            if (validarNombre(tfNombre.getText()) == true && validarApellido(tfApellido.getText()) == true && validarDni(tfDni.getText()) ==true) {
               Ej2.altaPersonas(tfNombre.getText(),tfApellido.getText(),tfDni.getText());
               vaciarCampos(); 
               lNombreInvalido.setVisible(false);
               lApellidoInvalido.setVisible(false);
               lDniInvalido.setVisible(false);
            }
            
            
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        Ej2.cerrarVentanaAlta();
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lApellidoInvalido;
    private javax.swing.JLabel lDniInvalido;
    private javax.swing.JLabel lError;
    private javax.swing.JLabel lNombreInvalido;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    private void vaciarCampos() {
        tfNombre.setText("");
        tfApellido.setText("");
        tfDni.setText("");
    }


    private Boolean validarNombre(String nombre) {
        Pattern pat = Pattern.compile("^[A-Z][a-z]{2,}$");
        Matcher mat = pat.matcher(nombre);
        if (mat.matches()) {
            return true;
        }else
            lNombreInvalido.setVisible(true);
            return false;
    }

    private Boolean validarApellido(String apellido) {
        Pattern pat = Pattern.compile("^[A-Z][a-z]{2,}$");    
        Matcher mat = pat.matcher(apellido);
        if (mat.matches()) {
            return true;
        }else
            lApellidoInvalido.setVisible(true);
            return false;
        
    }

    private Boolean validarDni(String dni) {
        Pattern pat = Pattern.compile("^[0-9]{8}[ABCDEFGHJKLMNPQRSTWXYZ]$");    
        Matcher mat = pat.matcher(dni);
        if (mat.matches()) {
            return true;
        }else
            lDniInvalido.setVisible(true);
            return false;   
    }
}
